# Generated by Django 4.2.7 on 2024-07-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
