# Generated by Django 4.2.7 on 2024-07-26 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_team_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='description',
        ),
        migrations.RemoveField(
            model_name='team',
            name='image',
        ),
    ]
