# Generated by Django 4.2.7 on 2024-07-20 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_dashboard.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
                ('breast_health', models.TextField(blank=True)),
                ('medical_history', models.TextField(blank=True)),
                ('mammogram_image', models.ImageField(blank=True, null=True, upload_to=user_dashboard.models.user_patient_directory_path)),
                ('risk_assessment_form', models.FileField(blank=True, null=True, upload_to=user_dashboard.models.user_patient_directory_path)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
