# Generated by Django 4.2.7 on 2024-07-20 22:45

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', blank=True, length=10, max_length=20, null=True, prefix=''),
        ),
    ]
