# Generated by Django 4.2.7 on 2024-07-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0015_remove_results_prediction_val_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='heatmap_image',
            field=models.ImageField(blank=True, null=True, upload_to='heatmaps/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='predicted_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='prediction_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
